### ISSUE TITLE
Feature Request: Support reversed kind and apiVersions

### ISSUE THREAD

**Issue by Teller-Ulam** [hickeyma/helm-mapkubeapis#21]
Sometimes I run into kind and apiVersion specified in the opposite order
The fix is to add the reversed one in Map.yaml i.e.

 - deprecatedAPI: "**kind: Deployment\napiVersion: extensions/v1beta1**"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"

It would be cool if this was supported automatically.
Thanks for the great work on this plugin!

**Comment by hickeyma** [comment]
@Teller-Ulam Thanks for raising this.

This is the reason that I pushed #14. Users seem to be finding different formats to the release manifests. As in your case, in different order. Others with comments on the line etc.

The usage of the configuration file ([map file](https://github.com/hickeyma/helm-mapkubeapis/blob/master/config/Map.yaml)) enables users to add search/replace patterns on the fly. To help with this there is an OOTB map file provided which I will try and keep updated with deprecated and removed APIs. It will cover a set pattern and cases but cannot possibly cover all cases. This is why it is configurable on the fly so that users can make changes as need be.

I hope this helps answer your question.

**Comment by Teller-Ulam** [comment]
Thank you, that makes sense. I'll close this one.
